name: Minventory
version: 0.4.0-DEV
author: Shadow2hel
main: me.shadow2hel.minventory.Minventory
api-version: 1.19
commands:
  wipe:
    description: Does the wipe
    usage: /<command>
    permission: minventory.wipe
    default: op
  minvgui:
    description: Opens gui
    usage: /<command>
    permission: minventory.gui