name: Minventory
version: 0.2.0-DEV
author: Shadow2hel
main: me.shadow2hel.minventory.Minventory
api-version: 1.19
commands:
  wipe:
    description: Does the wipe
    usage: /<command>
    permission: minventory.wipe
  scheduleWipe:
    description: Does the wipe on schedule
    usage: /<command>
    permission: minventory.scheduleWipe